version: 0.0
os: linux
files:
  - source: /sample.war         # Path to the WAR file in your source (GitHub or S3)
    destination: /home/ec2-user/tomcat/webapps/  # Destination where Tomcat looks for WAR files

hooks:
  BeforeInstall:
    - location: install_dependencies.sh  # Custom script for installing dependencies, if needed
      timeout: 300
      runas: root
    - location: stop_tomcat.sh        # Script to stop Tomcat before deploying
      timeout: 300
      runas: root

  AfterInstall:
    - location: start_tomcat.sh      # Script to start Tomcat after deployment
      timeout: 300
      runas: root

  ApplicationStop:
    - location: stop_tomcat.sh      # Ensure Tomcat is stopped before deployment (can be a duplicate of BeforeInstall)
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start_tomcat.sh    # Ensure Tomcat is started after deployment (can be a duplicate of AfterInstall)
      timeout: 300
      runas: root


